#!/usr/bin/env bash
set -eu
set -o pipefail

directory=/etc/nixos

message="${1:-}"
if [ -z "$message" ]; then
    echo "Error no commit message specified"
    exit 1
fi

cp $directory/configuration.nix $directory/"$(hostname)"/configuration.nix 
git add -A
git commit -m "$message"
git push origin master
