#!/usr/bin/env bash
set -eu
set -o pipefail

directory=/etc/nixos
host_directory=$directory/$(hostname)

message="${1:-}"
if [ -z "$message" ]; then
    echo "Error no commit message specified"
    exit 1
fi

for file in $(ls $host_directory); do
    if [ -n "$(git diff "$host_directory/$file")" ]; then 
      echo "Error there are local changes to $file"
      exit 1
    fi
    cp $directory/$file $host_directory
done

git add -A
git commit -m "$message"
git push origin master
