#!/usr/bin/env bash
set -eu
set -o pipefail

directory=/etc/nixos
configuration=$directory/configuration.nix
host_configuration=$directory/$(hostname)/configuration.nix

message="${1:-}"
if [ -z "$message" ]; then
    echo "Error no commit message specified"
    exit 1
fi

if [ -n "$(git diff "$host_configuration")" ]; then 
    echo "Error there are local changes to $host_configuration"
    exit 1
fi

cp $configuration $host_configuration
git add -A
git commit -m "$message"
git push origin master
