#!/usr/bin/env bash
set -eu
set -o pipefail

directory=/etc/nixos
configuration=$directory/configuration.nix
host_configuration=$directory/$(hostname)/configuration.nix

if ! diff $configuration $host_configuration >/dev/null; then
    echo "Error: there are local changes to $configuration"
    exit 1
fi

git pull
cp $host_configuration $configuration

