#!/usr/bin/env bash
set -eu
set -o pipefail

directory=/etc/nixos
host_directory=$directory/$(hostname)

for file in $(ls $host_directory); do
  if ! diff $directory/$file $host_directory/$file >/dev/null; then
    echo "Error: there are local changes to $directory/$file"
    exit 1
  fi
done

exit 0

git pull
cp $host_directory/* $directory

